In [4]:
#1. You are given a space separated list of numbers.
# Your task is to print a reversed NumPy array with the element type float.

import numpy as np
a=np.array(input().split(" "),float)
rev=a[::-1]
print("Resultant reversed array will be:",rev)

1 2 3 4 -8 -10
Resultant reversed array will be: [-10.  -8.   4.   3.   2.   1.]


In [11]:
#2. You are given a space separated list of nine integers. Your task is to convert this list into a M X N NumPy array.

import numpy as np

lst = np.array(input().split(' '), int)
print(lst.reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
#3. You are given a M X N integer array matrix with space separated elements (M = rows and N = columns).
# Your task is to print the transpose and flatten results.

import numpy as np

M=int(input("Enter no. of rows:"))
N=int(input("Enter no. of columns:"))

lst = np.array(input().split(' '), int)
matrix= lst.reshape(M, N)
print(matrix)

print("Transpose of a matrix:",np.transpose(matrix))
print("Flattened array:",matrix.flatten())


Enter no. of rows:3
Enter no. of columns:2
2 2 1 2 3 4
[[2 2]
 [1 2]
 [3 4]]
Transpose of a matrix: [[2 1 3]
 [2 2 4]]
Flattened array: [2 2 1 2 3 4]


In [42]:
#4. You are given two integer arrays of size N X P and M X P(N & M are rows, and P is the column). Your task is to 
# concatenate the arrays along axis 0.

import numpy as np

n,m,p = map(int,input().split())

A = np.array([input().split() for _ in range(n)],int)
B = np.array([input().split() for _ in range(m)],int)
print(np.concatenate((A,B),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [50]:
#5. You are given the shape of the array in the form of space-separated integers, each integer representing the size 
# of different dimensions, your task is to print an array of the given shape and integer type using the tools 
# numpy.zeros and numpy.ones.

import numpy as np
shape= tuple(map(int,input().split()))
print(np.zeros(shape,int), np.ones(shape,int), sep='\n')

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [5]:
#6. Your task is to print an array of size N X M with its main diagonal elements as 1's and 0's everywhere else.

import numpy as np
n,m = map(int,input().split())
eye = np.eye(n, m)
print(eye)

3 3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#7. You are given two integer arrays, A and B of dimensions X.
# Your task is to perform the following operations: add, subtract, multiply, integer division, mod, power

import numpy as np
n,m = map(int,input().split())

A = np.array(input().split(' '), int)
B = np.array(input().split(' '), int)

print("array:",A)
print("array:",B)

print("Addition:",np.add(A,B))
print("Subtraction:",np.subtract(A,B))
print("Multiply:",np.multiply(A,B))
print("Integer Division:",np.divide(A,B))
print("Mod:",np.mod(A,B))
print("Power:",np.power(A,B))

1 4
1 2 3 4
5 6 7 8
array: [1 2 3 4]
array: [5 6 7 8]
Addition: [ 6  8 10 12]
Subtraction: [-4 -4 -4 -4]
Multiply: [ 5 12 21 32]
Integer Division: [0.2        0.33333333 0.42857143 0.5       ]
Mod: [1 2 3 4]
Power: [    1    64  2187 65536]


In [9]:
#8. You are given a 1-D array,A . Your task is to print the floor,ceil and rint of all the elements of A.

import numpy as np

A = np.array(input().split(' '), float)

print(np.floor(A))
print(np.ceil(A))
print(np.rint(A))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  6.  7.  8.  9. 10.]


In [20]:
#9. You are given a 2-D array with dimensions N X M.
# Your task is to perform the sum tool over axis 0 and then find the product of that result.

import numpy as np
n,m = map(int,input().split())
A= np.array([input().split() for _ in range(n)],int)
#print(np.sum(A,axis=0))
print(np.prod(np.sum(A,axis=0)))

2 2
1 2
3 4
24


In [18]:
#10. You are given a 2-D array with dimensions N X M.
# Your task is to perform the min function over axis 1 and then find the max of that.

import numpy as np
n,m=map(int,input().split())
A = np.array([input().split() for _ in range(n)],int)
print(np.min(A,axis=1))
print(np.max(np.min(A,axis=1)))

4 2
2 5
3 7
1 3
4 0
[2 3 1 0]
3


In [21]:
#11. You are given a 2-D array of size N X M.
# Your task is to find:
# The mean along axis 1
# The var along axis 0
# The std along axis None.

import numpy as np
n,m=map(int,input().split())
A = np.array([input().split() for _ in range(n)],int)
print(np.mean(A,axis=1))
print(np.var(A,axis=0))
print(np.std(A,axis=None))

2 2
1 2
3 4
[1.5 3.5]
[1. 1.]
1.118033988749895


In [24]:
#12. You are given two arrays A and B. Both have dimensions of N X N.
# Your task is to compute their matrix product.

import numpy as np
n=int(input())
A=np.array([input().split() for _ in range(n)],int)
B=np.array([input().split() for _ in range(n)],int)
np.dot(A,B)

2
1 2
3 4
1 2
3 4


array([[ 7, 10],
       [15, 22]])

In [25]:
#13. You are given two arrays: A and B.
# Your task is to compute their inner and outer product.

import numpy as np

A = np.array(input().split(' '), int)
B = np.array(input().split(' '), int)

print(np.inner(A,B))
print(np.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [28]:
#14. You are given the coefficients of a polynomial P.
# Your task is to find the value of P at point x.

import numpy
n = list(map(float,input().split()));
m = input();
print(numpy.polyval(n,int(m)));

1.1 2 3
0
3.0


In [36]:
#You are given a square matrix A with dimensions N X N. Your task is to find the determinant. 
# Note: Round the answer to 2 places after the decimal.

import numpy as np
m=int(input())

A=np.array([input().split() for _ in range(m)],float)
print(round(np.linalg.det(A),2))

2
1.1 1.1
1.1 1.2
0.11
